/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import AccesoDatos.PropiedadData;
import Entidades.PropiedadInmueble;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kalema
 */
public class VistaContratoAlquiler extends javax.swing.JFrame {
    
    public DefaultTableModel modelo = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int f, int c){
            return false;
        }
    };
    
    private List<PropiedadInmueble> listaPropiedades = new ArrayList();
    private PropiedadInmueble lasProp=null;
    private PropiedadData abmPropiedadData= new PropiedadData();
    

    /**
     * Creates new form ContratoAlquiler
     */
    public VistaContratoAlquiler() {
        initComponents();
        armoTablaProp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPanelInquilino = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPDatosInquilino = new javax.swing.JPanel();
        jcbInquilinos = new javax.swing.JComboBox<>();
        omitirjLabel1 = new javax.swing.JLabel();
        jEtiquetaId = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelContratoPropiedad = new javax.swing.JPanel();
        omitirEtiqueta2 = new javax.swing.JLabel();
        jcbInquilinoProp = new javax.swing.JComboBox<>();
        jEtiquetaID = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        omitirEtiqueta3 = new javax.swing.JLabel();
        omitirEtiqueta4 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        omitirEtiqueta5 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        omitirEtiqueta6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        omitirEtiqueta7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaSeleccionPropiedad = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPanelInquilino.setForeground(new java.awt.Color(153, 153, 153));

        jPDatosInquilino.setBackground(new java.awt.Color(206, 238, 250));

        omitirjLabel1.setText("Inquilino");
        omitirjLabel1.setFocusable(false);

        jEtiquetaId.setForeground(new java.awt.Color(153, 153, 153));
        jEtiquetaId.setText("ID");
        jEtiquetaId.setFocusable(false);

        javax.swing.GroupLayout jPDatosInquilinoLayout = new javax.swing.GroupLayout(jPDatosInquilino);
        jPDatosInquilino.setLayout(jPDatosInquilinoLayout);
        jPDatosInquilinoLayout.setHorizontalGroup(
            jPDatosInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosInquilinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDatosInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(omitirjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEtiquetaId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jcbInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(672, Short.MAX_VALUE))
        );
        jPDatosInquilinoLayout.setVerticalGroup(
            jPDatosInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDatosInquilinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDatosInquilinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(omitirjLabel1))
                .addGap(18, 18, 18)
                .addComponent(jEtiquetaId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPDatosInquilino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPDatosInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jTabbedPanelInquilino.addTab("Contratos por Inquilinos", jPanel1);

        jPanelContratoPropiedad.setBackground(new java.awt.Color(245, 232, 232));

        omitirEtiqueta2.setText("Inquilino");
        omitirEtiqueta2.setFocusable(false);

        jEtiquetaID.setForeground(new java.awt.Color(153, 153, 153));
        jEtiquetaID.setText("IDPropiedad");
        jEtiquetaID.setFocusable(false);

        omitirEtiqueta3.setText("Fecha Inicio");
        omitirEtiqueta3.setFocusable(false);

        omitirEtiqueta4.setText("Fecha Final");
        omitirEtiqueta4.setFocusable(false);

        omitirEtiqueta5.setText("Fecha Realizado");
        omitirEtiqueta5.setFocusable(false);

        omitirEtiqueta6.setText("Vendedor");
        omitirEtiqueta6.setFocusable(false);

        omitirEtiqueta7.setText("Disponibilidad");
        omitirEtiqueta7.setFocusable(false);

        jButton1.setText("Contratar");

        jButton2.setText("Modificar");

        jButton3.setText("Cancelar");

        javax.swing.GroupLayout jPanelContratoPropiedadLayout = new javax.swing.GroupLayout(jPanelContratoPropiedad);
        jPanelContratoPropiedad.setLayout(jPanelContratoPropiedadLayout);
        jPanelContratoPropiedadLayout.setHorizontalGroup(
            jPanelContratoPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContratoPropiedadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContratoPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContratoPropiedadLayout.createSequentialGroup()
                        .addComponent(omitirEtiqueta2)
                        .addGap(18, 18, 18)
                        .addComponent(jcbInquilinoProp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jEtiquetaID, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelContratoPropiedadLayout.createSequentialGroup()
                        .addGroup(jPanelContratoPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelContratoPropiedadLayout.createSequentialGroup()
                                .addComponent(omitirEtiqueta3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelContratoPropiedadLayout.createSequentialGroup()
                                .addComponent(omitirEtiqueta6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelContratoPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelContratoPropiedadLayout.createSequentialGroup()
                                .addComponent(omitirEtiqueta7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelContratoPropiedadLayout.createSequentialGroup()
                                .addComponent(omitirEtiqueta4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelContratoPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelContratoPropiedadLayout.createSequentialGroup()
                                        .addComponent(omitirEtiqueta5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelContratoPropiedadLayout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3)))))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanelContratoPropiedadLayout.setVerticalGroup(
            jPanelContratoPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContratoPropiedadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContratoPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(omitirEtiqueta2)
                    .addComponent(jcbInquilinoProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEtiquetaID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanelContratoPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(omitirEtiqueta3)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(omitirEtiqueta4)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(omitirEtiqueta5)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanelContratoPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(omitirEtiqueta6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(omitirEtiqueta7)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelContratoPropiedadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTablaSeleccionPropiedad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablaSeleccionPropiedad);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addComponent(jPanelContratoPropiedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContratoPropiedad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPanelInquilino.addTab("Contratos por Propiedad", jPanel2);

        jLabel1.setText("GESTIÓN DE CONTRATOS DE ALQUILER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanelInquilino)
            .addGroup(layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jTabbedPanelInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPanelInquilino.getAccessibleContext().setAccessibleName("separadorInquilino");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaContratoAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaContratoAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaContratoAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaContratoAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaContratoAlquiler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jEtiquetaID;
    private javax.swing.JLabel jEtiquetaId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPDatosInquilino;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelContratoPropiedad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPanelInquilino;
    private javax.swing.JTable jTablaSeleccionPropiedad;
    private javax.swing.JComboBox<String> jcbInquilinoProp;
    private javax.swing.JComboBox<String> jcbInquilinos;
    private javax.swing.JLabel omitirEtiqueta2;
    private javax.swing.JLabel omitirEtiqueta3;
    private javax.swing.JLabel omitirEtiqueta4;
    private javax.swing.JLabel omitirEtiqueta5;
    private javax.swing.JLabel omitirEtiqueta6;
    private javax.swing.JLabel omitirEtiqueta7;
    private javax.swing.JLabel omitirjLabel1;
    // End of variables declaration//GEN-END:variables

    private void armoTablaProp(){
        modelo.addColumn("id"); //0
        modelo.addColumn("Zona"); //1
        modelo.addColumn("Dirección"); //2
        modelo.addColumn("Tipo local"); //3
        modelo.addColumn("Precio"); //4
        modelo.addColumn("Estado local"); //5
        modelo.addColumn("Inspector"); //6
        modelo.addColumn("Vendedor"); //7
        modelo.addColumn("Disponibilidad"); //8
        modelo.addColumn("Propietario"); //9
        modelo.addColumn("Caracteristicas"); //10
        modelo.addColumn("Accesibilidad"); //11
        jTablaSeleccionPropiedad.setModel(modelo);
    }
    
    private void cargoPropiedades(){
        listaPropiedades = abmPropiedadData.buscarPropiedad();
        for (PropiedadInmueble prop : listaPropiedades) {
            
        }
    }

}
